repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: detect-private-key
      - id: debug-statements
      - id: check-yaml
      - id: check-added-large-files
        args:
          - --maxkb=1024

  - repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --line-length=120
          - django
        language_version: python3
        exclude: ^django/node_modules/

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
        exclude: ^node_modules/
