services:
  web:
    build: .
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8187"
    volumes:
      - .:/code
    ports:
      - "8187:8187"
    depends_on:
      - selenium_firefox
      - db
      - redis
    stdin_open: true
    tty: true
    env_file:
      - dev.env

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - dev.env

  redis:
    image: redis

  selenium_firefox:
    container_name: selenium_firefox
    image: selenium/node-firefox-debug
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium_hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - "5901:5900"
    depends_on:
      - selenium_hub

  selenium_hub:
      container_name: selenium_hub
      image: selenium/hub
      ports:
        - "4444:4444"

  celery:
    build: .
    command: celery -A desafio_crawler worker --loglevel=debug
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
    restart: always
    env_file:
      - dev.env

  celery-beat:
    build: .
    command: celery -A desafio_crawler beat --scheduler django_celery_beat.schedulers:DatabaseScheduler --loglevel=debug
    volumes:
      - .:/code
    depends_on:
      - web
      - redis
    restart: always
    env_file:
      - dev.env


volumes:
  postgres_data: